### ISSUE TITLE
spotsInBox not working

### ISSUE THREAD

**Issue by vrrenske** [veeninglab/BactMAP#11]
The function which connects spot (fluorescence) data to mesh (segmentation) data from 2 different sources, is giving out an error. This can cause errors in:

`spotsInBox()`
`objectsInBox()`
`createPlotList()`

I am working on the resolution of this at the moment and will keep you updated.

**Comment by vrrenske** [comment]
The issue is now resolved in the development version of BactMAP. Please use 

```r
remotes::install_github("vrrenske/bactmap")
```

to install bactMAP until the next update if you want to use this functionality.

**Comment by 0Bernhard** [comment]
Hello 

I downloaded it from your repository but i am still getting an error. Is this something somone else has seen?

thank you


> plots_Bacillus <- createPlotList(spotdata=spots_Bacillus$spotframe,
+                                  meshdata=mesh_Bacillus$mesh,
+                                  groups=5)
Did not find cell data in spot dataset. Running spotsInBox to connect spots to meshes...
Package 'SDMTools' needed for this function to work. Press 'y' to install, or any other key to cancel.y
Installing package into ‘C:/Users/Berni/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
=======Error in loadNamespace(name) : there is no package called ‘SDMTools’
In addition: Warning message:
package ‘SDMTools’ is not available (for R version 3.6.3) 
>

**Comment by vrrenske** [comment]
Hi! I will double check this week. The package SDMTools is deprecated in the latest function of CRAN. I thought I replaced the SDMTools functions completely in the version of my repository - but it looks like I missed one function. I will keep you posted!

**Comment by vrrenske** [comment]
I forgot to update that now it is resolved in the development version on my repository (vrrenske/bactmap). 
I am working on an update of the "stable" version this week that has all the bug fixes of the last months.
